---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: a77cfeb3a886f97018f0a968fd3fe84031b2259e
    app.quarkus.io/build-timestamp: 2023-07-31 - 20:14:51 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 0.1.5
    app.kubernetes.io/name: mba
  name: mba
  namespace: mba
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mba-view
  namespace: mba
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: mba
    namespace: mba
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: a77cfeb3a886f97018f0a968fd3fe84031b2259e
    app.quarkus.io/build-timestamp: 2023-07-31 - 20:14:51 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: mba
    app.kubernetes.io/version: 0.1.5
    app.kubernetes.io/managed-by: quarkus
  name: mba
  namespace: mba
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: mba
    app.kubernetes.io/version: 0.1.5
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: a77cfeb3a886f97018f0a968fd3fe84031b2259e
    app.quarkus.io/build-timestamp: 2023-07-31 - 20:14:51 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 0.1.5
    app.kubernetes.io/name: mba
  name: mba
  namespace: mba
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.1.5
      app.kubernetes.io/name: mba
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: a77cfeb3a886f97018f0a968fd3fe84031b2259e
        app.quarkus.io/build-timestamp: 2023-07-31 - 20:14:51 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 0.1.5
        app.kubernetes.io/name: mba
      namespace: mba
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/maurycy_krzeminski/mba:0.1.5
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: mba
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: mba
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: a77cfeb3a886f97018f0a968fd3fe84031b2259e
    app.quarkus.io/build-timestamp: 2023-07-31 - 20:14:51 +0000
  labels:
    app.kubernetes.io/name: mba
    app.kubernetes.io/version: 0.1.5
    app.kubernetes.io/managed-by: quarkus
  name: mba
  namespace: mba
spec:
  ingressClassName: nginx
  rules:
    - host: mba.localhost
      http:
        paths:
          - backend:
              service:
                name: mba
                port:
                  name: http
            path: /
            pathType: Prefix
