apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongodb
  namespace: mba
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo