---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 2d8211910ccb6106bf43ada8a115cedff50b1fef
    app.quarkus.io/build-timestamp: 2023-07-16 - 05:33:50 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: dsa
    app.kubernetes.io/version: 0.1.4-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: dsa
  namespace: dsa
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: dsa
    app.kubernetes.io/version: 0.1.4-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 2d8211910ccb6106bf43ada8a115cedff50b1fef
    app.quarkus.io/build-timestamp: 2023-07-16 - 05:33:50 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 0.1.4-SNAPSHOT
    app.kubernetes.io/name: dsa
  name: dsa
  namespace: dsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.1.4-SNAPSHOT
      app.kubernetes.io/name: dsa
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 2d8211910ccb6106bf43ada8a115cedff50b1fef
        app.quarkus.io/build-timestamp: 2023-07-16 - 05:33:50 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 0.1.4-SNAPSHOT
        app.kubernetes.io/name: dsa
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/maurycy_krzeminski/dsa:0.1.4-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: dsa
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 2d8211910ccb6106bf43ada8a115cedff50b1fef
    app.quarkus.io/build-timestamp: 2023-07-16 - 05:33:50 +0000
  labels:
    app.kubernetes.io/name: dsa
    app.kubernetes.io/version: 0.1.4-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: dsa
  namespace: dsa
spec:
  ingressClassName: nginx
  rules:
    - host: dsa.localhost
      http:
        paths:
          - backend:
              service:
                name: dsa
                port:
                  name: http
            path: /
            pathType: Prefix
