---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 74f09601c8d3d5bd5e48336d91d40060fa24cb95
    app.quarkus.io/build-timestamp: 2023-07-15 - 15:01:32 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/version: 0.1.4-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: auth
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: auth
    app.kubernetes.io/version: 0.1.4-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 74f09601c8d3d5bd5e48336d91d40060fa24cb95
    app.quarkus.io/build-timestamp: 2023-07-15 - 15:01:32 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 0.1.4-SNAPSHOT
    app.kubernetes.io/name: auth
  name: auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.1.4-SNAPSHOT
      app.kubernetes.io/name: auth
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 74f09601c8d3d5bd5e48336d91d40060fa24cb95
        app.quarkus.io/build-timestamp: 2023-07-15 - 15:01:32 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 0.1.4-SNAPSHOT
        app.kubernetes.io/name: auth
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_OIDC_TOKEN_ISSUER
              value: http://keycloak:8080/realms/quarkus
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: http://keycloak:8080/realms/quarkus
          image: quay.io/maurycy_krzeminski/auth:0.1.4-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: auth
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 74f09601c8d3d5bd5e48336d91d40060fa24cb95
    app.quarkus.io/build-timestamp: 2023-07-15 - 15:01:32 +0000
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/version: 0.1.4-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: auth
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: auth.localhost
      http:
        paths:
          - backend:
              service:
                name: auth
                port:
                  name: http
            path: /
            pathType: Prefix
